### PR TITLE
Add async variants of all commands

### PR DESCRIPTION
**Pull request by joshuawright11**
Passthrough functions for all commands that calls the ELF variant with `.get()`.

### CODE REVIEW

**Review by 0xTim — APPROVED** [review]
Thanks! This is a great start to adopting concurrency in the library

**Comment by 0xTim** [comment]
@swift-server-bot please test

**Comment by 0xTim** [comment]
@swift-server-bot add to allowlist

**Comment by joshuawright11** [comment]
@0xTim thanks! I'm seeing errors in CI seemingly unrelated to this PR -

1. `error: redundant conformance of 'Gauge' to protocol 'Sendable'` in Swift 5.7 🤔 
2. some Swift 6 errors on nightly

Any ideas what those might be? Can we drop 5.7 support?

**Comment by 0xTim** [comment]
@joshuawright11 yeah I think we can drop 5.7 since NIO doesn't support it any more.

Nightly errors can potentially be ignored as well

**Comment by joshuawright11** [comment]
@0xTim this is embarrassing but I'm not super familiar with Jenkins - it seems like configs aren't actually in this repo and someone with access to `https://ci.swiftserver.group/` would need to disable the 5.6?

It's also throwing the same error as `nightly` on the `api breakage` pipeline - not sure what the solution is there.

**Review by fabianfett — CHANGES_REQUESTED** [review]
@joshuawright11 Thank you for this PR. Sorry for taking so long to review it. At the moment I'm not in favor of merging the PR. The PR uses the ELF API and uses the ELF's `.get()` call on top of it. Given that we don't have a real async API today this is an understandable approach. 

However this also means that we will need to touch a lot of code once we do have a real async interface. For this reason I'm not in favor of merging this PR today. I hope you can follow my thoughts. If you have any questions, please reach out.

**Comment by joshuawright11** [comment]
@fabianfett got it - thanks for the reply, my bad for jumping on this PR instead of waiting for a response to my issue!

Glad to hear this repo is still maintained and I look forward to a fully async await version someday 😊

**Pull request closed without merging**
